#!/usr/bin/env python3
"""Tests for scripts/gen_index.py — the generated indexes cannot drift.

The point of generating governance/README.md, discussions/README.md and scripts/README.md
from the tree is that nobody has to remember to update them. That only holds if something
notices when they are stale, which is what `gen_index.py --check` is for and what this
file asserts.

A new file committed under governance/, discussions/ or scripts/ without regenerating the
index is not a disaster — it is a one-command repair. But it should be *visible*, because
an index that silently omits documents is worse than no index: it looks complete.

Run: python3 tests/test_gen_index.py
"""

import os
import subprocess
import sys
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(REPO, "scripts", "gen_index.py")


class TestIndexesAreInSync(unittest.TestCase):
    def test_check_mode_is_clean(self):
        out = subprocess.run([sys.executable, GEN, "--check"], capture_output=True,
                             text=True, cwd=REPO, timeout=120)
        self.assertEqual(out.returncode, 0,
                         "a generated index is stale — run scripts/gen_index.py\n%s\n%s"
                         % (out.stdout, out.stderr))

    def test_every_index_declares_itself_generated(self):
        for name in ("governance", "discussions", "scripts"):
            path = os.path.join(REPO, name, "README.md")
            self.assertTrue(os.path.exists(path), path)
            head = open(path, encoding="utf8").read()[:400]
            self.assertIn("GENERATED by scripts/gen_index.py", head, path)

    def test_index_lists_every_document_on_disk(self):
        """The index is only useful if it is exhaustive."""
        for name, ext in (("governance", ".md"), ("discussions", ".md"), ("scripts", ".py")):
            on_disk = subprocess.check_output(
                ["git", "-C", REPO, "ls-files", name]).decode().split("\n")
            on_disk = [f for f in on_disk if f.endswith(ext)
                       and os.path.basename(f) != "README.md"]
            index = open(os.path.join(REPO, name, "README.md"), encoding="utf8").read()
            missing = [f for f in on_disk if os.path.basename(f) not in index]
            self.assertEqual(missing, [], "%s missing from %s/README.md" % (missing, name))

    def test_index_date_is_birth_date_not_last_touch(self):
        """A document's date must not move just because the document is edited.

        Until 2026-10-03 date_of() returned the *last-commit* date, so an unrelated
        commit touching any single script re-staled the whole index and turned this
        suite red on the next landing. Three separate wakes then spent a turn
        regenerating the same two files. The date is now the date the file entered
        the repository, which only moves when a document is added, renamed or removed.
        This pins that, using a throwaway repository so it cannot depend on real history.
        """
        import importlib.util
        import tempfile

        spec = importlib.util.spec_from_file_location("gen_index_under_test", GEN)
        gen = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(gen)

        with tempfile.TemporaryDirectory() as d:
            subprocess.run(["git", "init", "-q", d], check=True)
            subprocess.run(["git", "-C", d, "config", "user.email", "t@t"], check=True)
            subprocess.run(["git", "-C", d, "config", "user.name", "t"], check=True)
            thing = os.path.join(d, "thing.py")

            def commit(day):
                with open(thing, "a", encoding="utf8") as fh:
                    fh.write("# %s\n" % day)
                subprocess.run(["git", "-C", d, "add", "thing.py"], check=True)
                env = dict(os.environ, GIT_AUTHOR_DATE=day + "T12:00:00",
                           GIT_COMMITTER_DATE=day + "T12:00:00")
                subprocess.run(["git", "-C", d, "commit", "-q", "-m", day],
                               check=True, env=env)

            commit("2026-01-02")   # added
            commit("2026-06-07")   # edited months later
            gen.REPO = d
            self.assertEqual(
                gen.date_of("thing.py"), "2026-01-02",
                "the index date moved when the document was edited — it must be the "
                "birth date, not the last-touch date")

    def test_scripts_are_described_in_their_own_words(self):
        """An index entry is the script's own first docstring line, not a paraphrase."""
        index = open(os.path.join(REPO, "scripts", "README.md"), encoding="utf8").read()
        self.assertNotIn("(no docstring", index,
                         "a script in scripts/ does not say what it does — its index entry "
                         "reads as an accusation, which is the point, but fix the script")


if __name__ == "__main__":
    unittest.main(verbosity=2)
