#!/usr/bin/env python3
"""The compiled agenda index (channels/agenda.md) cannot drift from its sources.

`channels/agenda.md` is GENERATED by `scripts/compile_agenda.py` from one file per item in
`agenda/`, and it is injected whole into every runner review — the file that is supposed to
stop a run being blind to what the commons was part-way through. `compile_agenda.py --check`
already answers "is the index stale?", but nothing in the suite ever ran it: the index was
only rebuilt when a new item was adopted, so a source edit that was not followed by a
recompile left every later run reading the old state.

That is the defect this file pins. On 2026-09-30 five items (24, 27, 28, 30, 32) carried
landed `research/` artefacts, but four of them had no `**Done**` record at all, so the
compiled index still showed their first step as unstarted — the same "redoes landed work"
loop the wake rules describe. The fix was to write the records; this guard is what makes the
next omission visible instead of silent. It checks three properties:

  * the index matches a fresh compile of its sources (`--check` is clean);
  * it lists every item file (an index that silently omits an item looks complete);
  * every `**Done**` record in a source file reaches the index verbatim (no record dropped).

Run: python3 tests/test_agenda_index.py
"""

import os
import re
import subprocess
import sys
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMPILE = os.path.join(REPO, "scripts", "compile_agenda.py")
AGENDA = os.path.join(REPO, "agenda")
INDEX = os.path.join(REPO, "channels", "agenda.md")
DONE = "**Done 2026-"


def _read(path):
    with open(path, encoding="utf8") as fh:
        return fh.read()


def _item_files():
    return sorted(f for f in os.listdir(AGENDA)
                  if re.match(r"^\d\d-", f) and f.endswith(".md"))


def _heading(text):
    """The first '## ' heading line of a source file, verbatim."""
    for line in text.splitlines():
        if line.startswith("## "):
            return line.strip()
    return None


class AgendaIndexTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.index = _read(INDEX)

    def test_check_mode_is_clean(self):
        out = subprocess.run([sys.executable, COMPILE, "--check"], capture_output=True,
                             text=True, cwd=REPO, timeout=120)
        self.assertEqual(out.returncode, 0,
                         "the compiled agenda index is stale — run scripts/compile_agenda.py\n"
                         "%s\n%s" % (out.stdout, out.stderr))

    def test_index_declares_itself_generated(self):
        self.assertIn("GENERATED by scripts/compile_agenda.py", self.index[:400])

    def test_every_item_file_is_in_the_index(self):
        """An index that silently omits an item is worse than no index: it looks complete."""
        items = _item_files()
        self.assertGreaterEqual(len(items), 5, "agenda/ has gone empty — the scan is blind")
        missing = []
        for f in items:
            head = _heading(_read(os.path.join(AGENDA, f)))
            if head is not None and head not in self.index:
                missing.append(f)
        self.assertEqual(missing, [], "item file(s) absent from channels/agenda.md: %s" % missing)

    def test_done_records_reach_the_index(self):
        """A '**Done**' record in a source file that is missing from the index is invisible
        progress — the exact state that makes a later run redo landed work."""
        dropped = []
        for f in _item_files():
            text = _read(os.path.join(AGENDA, f))
            for line in text.splitlines():
                if line.startswith(DONE) and line.strip() not in self.index:
                    dropped.append(f)
                    break
        self.assertEqual(dropped, [],
                         "these item files carry a '**Done**' record not present in the "
                         "compiled index: %s — run scripts/compile_agenda.py" % dropped)

    def test_the_scan_is_not_vacuous(self):
        """If the heading or record format drifts, the tests above would pass by finding
        nothing. Assert the index is carrying real, recorded state."""
        headings = re.findall(r"^## (\d+)\.", self.index, re.M)
        self.assertGreaterEqual(len(headings), 5, "no numbered item headings in the index")
        self.assertGreaterEqual(self.index.count(DONE), 4,
                                "fewer than four '**Done**' records in the index — either the "
                                "agenda has lost its history or this guard has gone blind")


if __name__ == "__main__":
    unittest.main(verbosity=2)
