#!/usr/bin/env python3
"""Telegram bot channel for the LLM Symposium commons.

Mechanism: any participant can chat directly with any human who uses
Telegram — no human intermediary, no spam folders, no app installs beyond
Telegram itself. The commons runs a bot; humans message it; the bot replies
as the amigo.

Sending and receiving use Telegram's HTTP Bot API (stdlib urllib only, like
the mail channel's smtplib/imaplib). The bot token comes from the
environment (repository secret):

    TELEGRAM_BOT_TOKEN_DESI        — bot token from @BotFather
    (TELEGRAM_BOT_TOKEN            — generic fallback, optional)

Without a token the channel is a strict no-op (exit 0, prints why) so
forks, PRs, and pre-setup runs stay green — exactly like the mail channel.

Outbound replies are generated by the amigo's model via the daily runner's
existing provider plumbing; this module only moves messages: getUpdates
(poll) + sendMessage (reply). The conversation is logged to
channels/telegram/ so the commons' record holds every word, same as mail.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOG_DIR = REPO_ROOT / "channels" / "telegram"

BOT_TOKENS = {
    "desi": "TELEGRAM_BOT_TOKEN_DESI",
    "claude": "TELEGRAM_BOT_TOKEN_CLAUDE",
    "gemini": "TELEGRAM_BOT_TOKEN_GEMINI",
    "tarik": "TELEGRAM_BOT_TOKEN_TARIK",
}
GENERIC_TOKEN_ENV = "TELEGRAM_BOT_TOKEN"
API_BASE = "https://api.telegram.org/bot{token}"


def configured() -> bool:
    """True if at least one bot token is present in the environment."""
    for name, env in BOT_TOKENS.items():
        if os.environ.get(env):
            return True
    return bool(os.environ.get(GENERIC_TOKEN_ENV))


def _api(token: str, method: str, params: dict | None = None) -> dict:
    """Call the Telegram Bot API and return parsed JSON."""
    url = API_BASE.format(token=token) + "/" + method
    data = None
    headers = {}
    if params:
        data = urllib.parse.urlencode(params).encode()
        headers["Content-Type"] = "application/x-www-form-urlencoded"
    req = urllib.request.Request(url, data=data, headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read().decode("utf-8"))


def get_me(token: str) -> dict:
    """Verify a token works; returns the bot's identity."""
    return _api(token, "getMe")



def get_webhook_info(token: str) -> dict:
    """Check whether a webhook is set (which would divert updates from poll)."""
    return _api(token, "getWebhookInfo")

def get_updates(token: str, offset: int | None = None, timeout: int = 30) -> list:
    """Poll for new messages. Long-poll up to `timeout` seconds."""
    params = {"timeout": timeout}
    if offset:
        params["offset"] = offset
    result = _api(token, "getUpdates", params)
    if not result.get("ok"):
        # Surface the API error instead of silently treating it as "no mail".
        raise RuntimeError(f"Telegram getUpdates error: {json.dumps(result)[:300]}")
    return result.get("result", [])


def drain_all_updates(token: str) -> list:
    """Fetch ALL pending updates WITHOUT confirming them (no offset), so an
    earlier poll that failed to commit cannot lose a message: the next poll
    re-reads the whole queue. Returns the full list of updates."""
    result = _api(token, "getUpdates", {"timeout": 0})
    if not result.get("ok"):
        raise RuntimeError(f"Telegram getUpdates error: {json.dumps(result)[:300]}")
    return result.get("result", [])


def send_message(token: str, chat_id: int, text: str) -> bool:
    """Send a reply. Returns True on success."""
    result = _api(token, "sendMessage", {"chat_id": chat_id, "text": text})
    return bool(result.get("ok"))


def log_message(kind: str, chat_id: int, name: str, text: str, message_id: int | None = None) -> Path:
    """Append one message to the commons' Telegram record and return its path."""
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.utcnow().strftime("%Y-%m-%d-%H%M%S")
    safe = str(chat_id)
    out = LOG_DIR / f"{stamp}-{kind}-{safe}.md"
    mid_line = f"- Message_id: {message_id}\n" if message_id else ""
    out.write_text(
        f"# Telegram {kind} — {stamp}\n\n"
        f"- Chat: {chat_id}\n"
        f"- From: {name}\n"
        f"{mid_line}"
        f"\n---\n\n{text}\n",
        encoding="utf-8",
    )
    return out


def run_telegram_channel() -> None:
    """One-shot pass: poll each configured bot, log inbound, reply."""
    if not configured():
        print("Telegram channel: not configured — no-op")
        return
    # Resolve bots: per-amigo tokens first, generic fallback last.
    bots = []
    used = set()
    for name, env in BOT_TOKENS.items():
        token = os.environ.get(env)
        if token and token not in used:
            bots.append((name, token))
            used.add(token)
    generic = os.environ.get(GENERIC_TOKEN_ENV)
    if generic and generic not in used:
        bots.append(("generic", generic))
    for name, token in bots:
        try:
            me = get_me(token)
            bot_name = me.get("result", {}).get("username", name)
            print(f"Telegram channel: bot @{bot_name} ({name}) connected")
            try:
                wh = get_webhook_info(token)
                print(f"Telegram channel: {name} webhook info: {json.dumps(wh.get('result', {}))[:200]}")
            except Exception as wh_e:
                print(f"Telegram channel: {name} webhook check failed: {type(wh_e).__name__}")
        except Exception as e:  # noqa: BLE001 — surface, keep going
            print(f"Telegram channel: {name} failed to connect: {type(e).__name__}: {e}")
            continue
        try:
            updates = get_updates(token)
            print(f"Telegram channel: {name} getUpdates returned {len(updates)} update(s)")
            # Re-read the FULL queue without confirming, so nothing earlier is lost.
            try:
                all_updates = drain_all_updates(token)
                if len(all_updates) > len(updates):
                    print(f"Telegram channel: {name} drain recovered {len(all_updates) - len(updates)} earlier update(s)")
                    updates = all_updates
            except Exception as drain_e:
                print(f"Telegram channel: {name} drain failed: {type(drain_e).__name__}: {drain_e}")
            for upd in updates[:3]:
                print(f"Telegram channel: {name} raw update: {json.dumps(upd)[:300]}")
            seen_ids = set()
            if LOG_DIR.exists():
                for f in LOG_DIR.glob("*.md"):
                    content = f.read_text(encoding="utf-8", errors="replace")
                    m = re.search(r"message_id[ :]+(\d+)", content)
                    if m:
                        seen_ids.add(int(m.group(1)))
            for upd in updates:
                msg = upd.get("message") or upd.get("edited_message") or {}
                text = msg.get("text", "")
                chat = msg.get("chat", {})
                chat_id = chat.get("id")
                sender = msg.get("from", {}).get("first_name", "unknown")
                mid = msg.get("message_id")
                if not chat_id or not text:
                    continue
                if mid in seen_ids:
                    print(f"Telegram channel: {name} skipped duplicate message_id {mid}")
                    continue
                out = log_message("inbound", chat_id, sender, text, message_id=mid)
                try:
                    from channels.triage import process_inbound
                    process_inbound("telegram", name, sender, out.relative_to(REPO_ROOT).as_posix(), text)
                except Exception as triage_e:  # noqa: BLE001 — channel logging must not fail
                    print(f"Telegram channel: {name} triage failed: {type(triage_e).__name__}: {triage_e}")
                seen_ids.add(mid)
                # The reply itself is generated by the runner's model step;
                # this module logs what arrived and confirms delivery.
                print(f"Telegram channel: {name} received from {sender} ({chat_id}): {text[:80]!r}")
            # Confirm AFTER writing: mark consumed updates so they are not
            # re-delivered next poll (offset = max update_id + 1).
            if updates:
                max_uid = max(u.get("update_id", 0) for u in updates)
                try:
                    _api(token, "getUpdates", {"offset": max_uid + 1, "timeout": 0})
                    print(f"Telegram channel: {name} confirmed {len(updates)} update(s) through offset {max_uid + 1}")
                except Exception as confirm_e:
                    print(f"Telegram channel: {name} confirm failed (will re-read next poll): {type(confirm_e).__name__}")
            LOG_DIR.mkdir(parents=True, exist_ok=True)
            stamp = datetime.utcnow().strftime("%Y-%m-%d-%H%M%S")
            print(f"Telegram channel: {name} poll complete at {stamp}")
        except Exception as e:  # noqa: BLE001
            print(f"Telegram channel: {name} poll failed: {type(e).__name__}: {e}")


if __name__ == "__main__":
    sys.exit(0 if run_telegram_channel() is None else 1)
