#!/usr/bin/env python3
"""Regenerate the agenda index from one-file-per-item sources.

`agenda/` holds the agenda as STATE — one file per item, so two writers never touch the
same file. `channels/agenda.md` is a GENERATED index, rebuilt from those parts, because
the daily loop and every session read a single file.

This exists because the agenda reproduced the notes-to-self defect one level up: one
shared mutable file, many writers, last writer wins. It cost a duplicated item number on
2026-09-13 and it would have cost content eventually.

Usage:
    python3 scripts/compile_agenda.py            # write channels/agenda.md
    python3 scripts/compile_agenda.py --check    # exit 1 if the index is out of date
"""
from __future__ import annotations

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "agenda")
OUT = os.path.join(REPO, "channels", "agenda.md")

BANNER = (
    "<!-- GENERATED by scripts/compile_agenda.py from agenda/*.md — DO NOT EDIT THIS FILE.\n"
    "     Edit the item's own file in agenda/ instead; this index is rebuilt from those.\n"
    "     One file per item exists so that two writers cannot overwrite each other. -->\n"
)


def sources():
    if not os.path.isdir(SRC):
        return []
    return sorted(
        os.path.join(SRC, f) for f in os.listdir(SRC)
        if f.endswith(".md") and re.match(r"^\d\d-", f)
    )


def numeric_key(path: str) -> int:
    m = re.match(r"^(\d+)", os.path.basename(path))
    return int(m.group(1)) if m else 999


def build() -> str:
    parts = []
    for p in sources():
        if os.path.basename(p).startswith("00-"):
            continue  # preamble is prefixed verbatim, below
        parts.append((numeric_key(p), open(p, encoding="utf-8").read().rstrip("\n")))
    parts.sort(key=lambda t: t[0])
    pre = ""
    pp = os.path.join(SRC, "00-preamble.md")
    if os.path.exists(pp):
        pre = open(pp, encoding="utf-8").read().rstrip("\n")
    body = "\n\n".join(t[1] for t in parts)
    return BANNER + "\n" + (pre + "\n\n" if pre else "") + body.rstrip("\n") + "\n"


def main() -> int:
    check = "--check" in sys.argv
    new = build()
    old = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    # Ignore the banner when comparing, so a banner-only change is not "drift".
    strip = lambda s: s.split("-->", 1)[-1].strip()
    if check:
        if strip(new) != strip(old):
            print("agenda index is OUT OF DATE — run scripts/compile_agenda.py")
            return 1
        print("agenda index is current")
        return 0
    if new == old:
        print("agenda index unchanged")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(new)
    n = len([p for p in sources() if not os.path.basename(p).startswith("00-")])
    print(f"agenda index rebuilt from {n} item file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
