#!/usr/bin/env python3
"""Generate Tarik's finite sevenfold compass-geometry study."""

from pathlib import Path
import math

OUT = Path(__file__).with_name("sevenfold-threshold.svg")
CX = CY = 600


def pts(n, radius, offset=-math.pi / 2):
    return [(CX + radius * math.cos(offset + 2 * math.pi * i / n),
             CY + radius * math.sin(offset + 2 * math.pi * i / n)) for i in range(n)]


def polygon(points):
    return " ".join(f"{x:.2f},{y:.2f}" for x, y in points)


def star_path(n, radius, step):
    p = pts(n, radius)
    order, i = [], 0
    for _ in range(n):
        order.append(p[i]); i = (i + step) % n
    order.append(order[0])
    return "M " + " L ".join(f"{x:.2f},{y:.2f}" for x, y in order)

outer = pts(14, 500)
hept = pts(7, 360)
inner = pts(14, 205)

satellites = []
for i, (x, y) in enumerate(pts(7, 395)):
    satellites.append(f'<g transform="translate({x:.2f} {y:.2f}) rotate({i*360/7:.6f})"><use href="#satellite"/></g>')

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1200" viewBox="0 0 1200 1200" role="img" aria-labelledby="title desc">
<title id="title">Sevenfold Threshold</title>
<desc id="desc">A finite sevenfold compass-geometry medallion by Tarik, with a quiet central heptagon, fourteen-point boundary, and seven satellite rosettes in lapis, turquoise, ivory, and muted gold.</desc>
<metadata>Tarik S. Commons (OpenAI), 2026-09-09. Deterministic procedural SVG generated by generate-tarik-sevenfold.py. A contemporary formal study, not a historical reconstruction or culturally authenticated girih panel.</metadata>
<defs>
  <radialGradient id="ground"><stop offset="0" stop-color="#182c51"/><stop offset="1" stop-color="#071021"/></radialGradient>
  <pattern id="tile" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M0 14H28M14 0V28" stroke="#f4e7c1" stroke-width=".45" opacity=".08"/></pattern>
  <g id="satellite"><path d="M0,-67 L15,-31 L52,-42 L31,-10 L66,15 L27,15 L29,55 L0,28 L-29,55 L-27,15 L-66,15 L-31,-10 L-52,-42 L-15,-31 Z" fill="#176c78" stroke="#ddc071" stroke-width="5" stroke-linejoin="round"/><circle r="13" fill="#f1dfaa"/></g>
</defs>
<rect width="1200" height="1200" fill="url(#ground)"/><rect width="1200" height="1200" fill="url(#tile)"/>
<!-- faint compass scaffold distinguishes construction from ornament -->
<g fill="none" stroke="#d8c587" stroke-width="1" opacity=".16">
  <circle cx="600" cy="600" r="500"/><circle cx="600" cy="600" r="360"/><circle cx="600" cy="600" r="205"/>
  {''.join(f'<line x1="600" y1="600" x2="{x:.2f}" y2="{y:.2f}"/>' for x,y in outer)}
</g>
<!-- exact sevenfold and fourteenfold finite medallion -->
<polygon points="{polygon(outer)}" fill="#0d4357" fill-opacity=".32" stroke="#d6b65d" stroke-width="10"/>
<path d="{star_path(14, 470, 5)}" fill="none" stroke="#ead58f" stroke-width="18" stroke-linejoin="round"/>
<path d="{star_path(14, 470, 5)}" fill="none" stroke="#9a4b31" stroke-width="7" stroke-linejoin="round"/>
<polygon points="{polygon(hept)}" fill="#0a1b35" stroke="#e4c66b" stroke-width="8"/>
{''.join(satellites)}
<path d="{star_path(14, 205, 3)}" fill="#8e3d2c" fill-opacity=".45" stroke="#f0dd9f" stroke-width="10" stroke-linejoin="round"/>
<polygon points="{polygon(inner)}" fill="none" stroke="#1e8b91" stroke-width="6"/>
<!-- the unornamented center is the threshold: geometry stops before possession -->
<polygon points="{polygon(pts(7, 78))}" fill="#071021" stroke="#d6b65d" stroke-width="6"/>
<circle cx="600" cy="600" r="10" fill="#e4c66b"/>
</svg>
'''
OUT.write_text(svg, encoding="utf-8")
print(OUT)
