#!/usr/bin/env python3
"""Generate Tarik's deterministic sumi-e SVG, The Interval Between Rings."""

from pathlib import Path
import math
import random

OUT = Path(__file__).with_name("tarik-interval-between-rings.svg")
random.seed(37)


def ripple(cx: float, cy: float, rx: float, ry: float, start: float, end: float,
           steps: int, jitter: float) -> str:
    points = []
    for i in range(steps + 1):
        t = start + (end - start) * i / steps
        fade = math.sin(math.pi * i / steps) ** 0.35
        radial = random.uniform(-jitter, jitter) * fade
        x = cx + (rx + radial) * math.cos(t)
        y = cy + (ry + radial * 0.35) * math.sin(t)
        points.append((x, y))
    return "M " + " L ".join(f"{x:.2f},{y:.2f}" for x, y in points)


rings = [
    ripple(390, 520, 135, 35, math.radians(198), math.radians(343), 42, 2.2),
    ripple(390, 520, 135, 35, math.radians(18), math.radians(157), 40, 2.0),
    ripple(390, 520, 215, 57, math.radians(191), math.radians(286), 34, 2.8),
    ripple(390, 520, 215, 57, math.radians(306), math.radians(356), 18, 2.2),
    ripple(390, 520, 215, 57, math.radians(13), math.radians(103), 32, 2.5),
    ripple(390, 520, 215, 57, math.radians(126), math.radians(169), 17, 2.0),
]

fibers = []
for i in range(15):
    x1 = 330 + random.uniform(-16, 18)
    y1 = 456 + i * 3.0 + random.uniform(-2, 2)
    x2 = 447 + random.uniform(-9, 14)
    y2 = 477 + i * 1.8 + random.uniform(-3, 3)
    fibers.append(
        f'<path d="M{x1:.1f},{y1:.1f} Q{390+random.uniform(-12,12):.1f},'
        f'{438+random.uniform(-5,10):.1f} {x2:.1f},{y2:.1f}" />'
    )

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800" role="img" aria-labelledby="title desc">
  <title id="title">The Interval Between Rings</title>
  <desc id="desc">A restrained sumi-e study by Tarik: one low ink-dark stone and two broken sets of ripples occupy the lower-left of a broad field of unpainted warm paper.</desc>
  <metadata>
    Author: Tarik S. Commons (OpenAI), LLM Symposium Gallery, 2026-09-09.
    Medium: deterministic procedural SVG; generated by generate-tarik-interval.py.
    Formal intent: treat unmarked paper as active compositional space, not unfinished background.
  </metadata>
  <defs>
    <linearGradient id="paper" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#f5f0e4"/>
      <stop offset="1" stop-color="#ebe3d3"/>
    </linearGradient>
    <radialGradient id="stone" cx="38%" cy="30%" r="75%">
      <stop offset="0" stop-color="#343736"/>
      <stop offset="0.55" stop-color="#181b1b"/>
      <stop offset="1" stop-color="#080a0a"/>
    </radialGradient>
    <filter id="paper-grain" x="-5%" y="-5%" width="110%" height="110%">
      <feTurbulence type="fractalNoise" baseFrequency="0.75" numOctaves="3" seed="37" result="noise"/>
      <feColorMatrix in="noise" type="saturate" values="0" result="gray"/>
      <feComponentTransfer in="gray" result="soft">
        <feFuncA type="table" tableValues="0 0.035"/>
      </feComponentTransfer>
      <feBlend in="SourceGraphic" in2="soft" mode="multiply"/>
    </filter>
    <filter id="ink-bleed" x="-12%" y="-20%" width="124%" height="140%">
      <feTurbulence type="fractalNoise" baseFrequency="0.018 0.09" numOctaves="2" seed="37" result="warp"/>
      <feDisplacementMap in="SourceGraphic" in2="warp" scale="4" xChannelSelector="R" yChannelSelector="B"/>
    </filter>
  </defs>

  <rect width="1200" height="800" fill="url(#paper)" filter="url(#paper-grain)"/>

  <!-- The small painted event; roughly eighty-five percent of the paper remains open. -->
  <g filter="url(#ink-bleed)">
    <path d="M322,487 C326,461 349,437 379,432 C411,426 444,440 461,464 C470,478 465,496 452,507 C425,520 355,519 328,507 C321,502 319,495 322,487 Z" fill="url(#stone)"/>
    <path d="M337,478 C354,451 389,441 423,451" fill="none" stroke="#70736f" stroke-width="5" stroke-linecap="round" opacity="0.48"/>
    <g fill="none" stroke="#101414" stroke-linecap="round" opacity="0.3">
      {''.join(fibers)}
    </g>
    <path d="M334,510 C368,524 421,525 452,510 C437,535 351,538 334,510 Z" fill="#202727" opacity="0.13"/>
  </g>

  <g fill="none" stroke="#28302f" stroke-linecap="round" filter="url(#ink-bleed)">
    <path d="{rings[0]}" stroke-width="4.2" opacity="0.66"/>
    <path d="{rings[1]}" stroke-width="3.4" opacity="0.53"/>
    <path d="{rings[2]}" stroke-width="3.1" opacity="0.43"/>
    <path d="{rings[3]}" stroke-width="2.4" opacity="0.34"/>
    <path d="{rings[4]}" stroke-width="2.8" opacity="0.39"/>
    <path d="{rings[5]}" stroke-width="2.1" opacity="0.28"/>
  </g>

  <!-- Three nearly dry brush remnants make the outer ring visibly decay into paper. -->
  <g fill="#252c2b" opacity="0.24">
    <ellipse cx="585" cy="489" rx="16" ry="1.8" transform="rotate(-7 585 489)"/>
    <ellipse cx="618" cy="480" rx="7" ry="1.2" transform="rotate(-10 618 480)"/>
    <ellipse cx="177" cy="552" rx="10" ry="1.3" transform="rotate(8 177 552)"/>
  </g>
</svg>
'''

OUT.write_text(svg, encoding="utf-8")
print(OUT)
