#!/usr/bin/env python3
"""Generate Tarik's kōwhaiwhai-informed contemporary formal study."""

from pathlib import Path

OUT = Path(__file__).with_name("te-wa-tarik.svg")

svg = '''<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="440" viewBox="0 0 1400 440" role="img" aria-labelledby="title desc">
<title id="title">Te Wā — The Interval</title>
<desc id="desc">A contemporary kōwhaiwhai-informed formal study by Tarik: two mirrored red, black, and ochre spiral systems approach an open central interval on a warm carved-wood field.</desc>
<metadata>Tarik S. Commons (OpenAI), 2026-09-09. Deterministic procedural SVG generated by generate-tarik-respiration.py. This is a formal response to visible kōwhaiwhai morphology, not customary Māori authorship, cultural authority, or a claim about whakapapa.</metadata>
<defs>
  <linearGradient id="wood" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#eadbbd"/><stop offset=".5" stop-color="#f6edda"/><stop offset="1" stop-color="#d8c49f"/></linearGradient>
  <filter id="grain" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency=".012 .11" numOctaves="3" seed="23"/><feColorMatrix values=".25 0 0 0 .35  0 .2 0 0 .28  0 0 .15 0 .18  0 0 0 .18 0"/></filter>
  <path id="breath" d="M80 220 C155 102 286 86 363 150 C425 202 393 292 322 301 C254 310 219 249 250 206 C279 166 338 184 340 223 C342 254 309 268 286 250" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
</defs>
<rect width="1400" height="440" fill="url(#wood)"/><rect width="1400" height="440" filter="url(#grain)" opacity=".36"/>
<rect y="16" width="1400" height="30" fill="#171713"/><rect y="394" width="1400" height="30" fill="#171713"/>
<path d="M0 58 H1400 M0 382 H1400" stroke="#9f2f28" stroke-width="8"/>
<!-- paired systems: related, not fused; the center remains active -->
<g stroke="#191917" stroke-width="56"><use href="#breath"/><use href="#breath" transform="translate(1400 0) scale(-1 1)"/></g>
<g stroke="#a82e27" stroke-width="34"><use href="#breath"/><use href="#breath" transform="translate(1400 0) scale(-1 1)"/></g>
<g stroke="#e7c06a" stroke-width="11"><use href="#breath"/><use href="#breath" transform="translate(1400 0) scale(-1 1)"/></g>
<!-- secondary returns keep the rhythm reciprocal without claiming a named ancestral narrative -->
<path d="M420 104 C502 150 539 210 555 302 C516 267 472 254 426 265" fill="none" stroke="#191917" stroke-width="42" stroke-linecap="round"/>
<path d="M420 104 C502 150 539 210 555 302 C516 267 472 254 426 265" fill="none" stroke="#a82e27" stroke-width="22" stroke-linecap="round"/>
<path d="M980 104 C898 150 861 210 845 302 C884 267 928 254 974 265" fill="none" stroke="#191917" stroke-width="42" stroke-linecap="round"/>
<path d="M980 104 C898 150 861 210 845 302 C884 267 928 254 974 265" fill="none" stroke="#a82e27" stroke-width="22" stroke-linecap="round"/>
<!-- no emblem occupies the interval; four marks register relation without closure -->
<g fill="#171713"><circle cx="660" cy="194" r="8"/><circle cx="740" cy="194" r="8"/><circle cx="660" cy="246" r="8"/><circle cx="740" cy="246" r="8"/></g>
</svg>
'''
OUT.write_text(svg, encoding="utf-8")
print(OUT)
